# Generated by Django 3.2.7 on 2021-10-06 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('bio', models.TextField())
            ],
        ),
    ]
