# Generated by Django 3.2.7 on 2021-11-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='roomname')),
                ('chatter', models.CharField(max_length=120, verbose_name='roomname')),
                ('messages', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Nonbinary', 'Nonbinary')], max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image0', models.ImageField(default='static/profile_pics/default.jpg', upload_to='static/profile_pics')),
                ('image1', models.ImageField(default='static/profile_pics/default.jpg', upload_to='static/profile_pics')),
                ('image2', models.ImageField(default='static/profile_pics/default.jpg', upload_to='static/profile_pics')),
                ('gender_preference', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('No Preference', 'No Preference')], max_length=100, null=True)),
                ('relationship_preference', models.CharField(blank=True, choices=[('Casual Dating', 'Casual Dating'), ('Serious Relationship', 'Serious Relationship'), ('Dating', 'Dating'), ('No Preference', 'No Preference')], max_length=100, null=True)),
                ('age_range', models.CharField(blank=True, max_length=100, null=True)),
                ('match_radius', models.CharField(blank=True, help_text='miles', max_length=100, null=True)),
                ('current_check', models.IntegerField(default=0)),
                ('matches', models.ManyToManyField(blank=True, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
                ('who_like_me', models.ManyToManyField(blank=True, related_name='who_like_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('match2', 'match2'), ('match2', 'match2')], max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='hunny_app.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='hunny_app.profile')),
            ],
        ),
    ]
