# Generated by Django 3.2.7 on 2021-11-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Nonbinary', 'Nonbinary')], max_length=100, null=True),
        ),
    ]
