# Generated by Django 3.2.7 on 2021-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
    ]
