# Generated by Django 3.2.7 on 2021-10-30 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunny_app', '0002_auto_20211026_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/img-01.jpg', upload_to='static/hunny_app/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_like_me',
            field=models.ManyToManyField(blank=True, related_name='who_like_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
