# Generated by Django 3.2.8 on 2021-10-31 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunny_app', '0002_auto_20211026_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='children_preference',
            field=models.CharField(blank=True, choices=[('Children are a dealbreaker', 'Children are a dealbreaker'), ('Looking for children in the future', 'Looking for children in the future'), ('Prefer someone with children', 'Prefer someone with children'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Nonbinary', 'Nonbinary')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_preference',
            field=models.CharField(blank=True, choices=[('Casual Dating', 'Casual Dating'), ('Serious Relationship', 'Serious Relationship'), ('Dating', 'Dating'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/signup.jpg', upload_to='static/hunny_app/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='match_radius',
            field=models.CharField(blank=True, help_text='miles', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_like_me',
            field=models.ManyToManyField(blank=True, related_name='who_like_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
