# Generated by Django 3.2.8 on 2021-10-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0002_auto_20211026_2307'),
        ('hunny_app', '0002_auto_20211027_1504'),
    ]

    operations = [
    ]
