# Generated by Django 3.2.7 on 2021-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Nonbinary', 'Nonbinary')], max_length=100, null=True),
        ),
    ]
