# Generated by Django 3.2.7 on 2021-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0003_auto_20211030_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='children_preference',
            field=models.CharField(blank=True, choices=[('Children are a dealbreaker', 'Children are a dealbreaker'), ('Looking for children in the future', 'Looking for children in the future'), ('Prefer someone with children', 'Prefer someone with children'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Nonbinary', 'Nonbinary')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_preference',
            field=models.CharField(blank=True, choices=[('Casual Dating', 'Casual Dating'), ('Serious Relationship', 'Serious Relationship'), ('Dating', 'Dating'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/signup.jpg', upload_to='static/hunny_app/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='match_radius',
            field=models.CharField(blank=True, help_text='miles', max_length=100),
        ),
    ]
