# Generated by Django 3.2.8 on 2021-11-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0004_message'),
        ('hunny_app', '0004_remove_profile_children_preference'),
    ]

    operations = [
    ]
