# Generated by Django 3.2.7 on 2021-10-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunny_app', '0003_merge_0002_auto_20211026_2307_0002_auto_20211027_1504'),
        ('hunny_app', '0004_auto_20211030_1542'),
    ]

    operations = [
    ]
